In [ ]:
import sys
from pathlib import Path

# Force notebook to recognize project root
import os
ROOT = Path(os.getcwd()).resolve().parents[0] # one level up from tests/
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

import pandas as pd
from src.inference_pipeline.inference import predict

# Load a few rows of already preprocessed data
sample_path = ROOT / "data/processed/feature_engineered_eval.csv"
df = pd.read_csv(sample_path).sample(5, random_state=42).reset_index(drop=True)

print("Input sample:")
display(df.head())

# Run inference
preds_df = predict(df)
print("✅ Predictions returned")
display(preds_df[["predicted_price"]].head())

Current working directory: c:\Users\vigne\Desktop\Rml\Regression_ML_EndtoEnd-main\tests
File exists: False
 Inference using project root: C:\Users\vigne\Desktop\Rml\Regression_ML_EndtoEnd-main
Input sample:

,year,quarter,month,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,...,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,lat,lng,zipcode_freq,city_full_encoded
0,2021,3,7,259900.0,145.396160,140.979244,104.0,98.0,107.0,66.0,...,10937.0,250.0,20604.0,20604.0,10007.0,255300.562038,NaN,NaN,94.0,150644.162953
1,2021,3,8,429000.0,253.164135,257.973734,82.0,95.0,117.0,126.0,...,0.0,0.0,0.0,0.0,0.0,450603.296700,NaN,NaN,94.0,531812.641036
2,2020,1,2,202500.0,99.965760,109.198464,94.0,115.0,140.0,157.0,...,31265.0,1746.0,52357.0,52357.0,27625.0,189474.969209,NaN,NaN,94.0,200659.462293
3,2020,2,6,539900.0,217.805198,217.108051,6.0,11.0,11.0,14.0,...,1251.0,30.0,1991.0,1991.0,1156.0,504649.454265,NaN,NaN,94.0,346254.422931
4,2021,3,7,749400.0,349.226265,339.058053,113.0,112.0,140.0,60.0,...,16826.0,681.0,31591.0,31591.0,14740.0,699558.033278,NaN,NaN,94.0,267769.134424

 Skipping city merge: no 'city_full' column present.
 Dropped 0 duplicate rows (excluding date/year).
 Removed 0 rows with median_list_price > 19M.
✅ Predictions returned

   predicted_price
0    239316.062500
1    418226.093750
2    203034.703125
3    534974.062500
4    679073.187500